language: python
python:
- '2.6'
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install software-properties-common python-setuptools libboost-python-dev
  libcfitsio3-dev
- sudo add-apt-repository -y ppa:radio-astro/main
- sudo apt-get update -qq
- sudo apt-get install libcasacore2-dev casacore-data
install:
- sudo pip install sphinx
- sudo pip install travis-sphinx
- python setup.py develop
script:
- nosetests
- travis-sphinx --nowarn -s doc build
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: cdrrma3XaFjtv4lHvag6dfhSbKBF8iLmVgPQEjXP8qa+WxHnkHObkyraYAFGqThDY/0lBdrBm7Og6l1JfAcSA2BjdPQYxujP8KEoVicPwlgwEJ5LZo4HqympWVk33APvbcYNw7K/CwEXNJCCD1tDiO4pdwkPAWuKlnYUVfZq2yI=
  on:
    tags: true
    repo: casacore/python-casacore
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08a570c12a3afa37d8e2

